name: compile-and-run-private-repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up SSH Agent
      run: |
        eval `ssh-agent -s`
        ssh-add - <<< "${{ secrets.PRIVATE_SSH_KEY }}"

    - name: Add GitHub to known hosts
      run: |
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

    - name: Clone the private repository
      run: |
        git clone git@github.com:FedericoCalzoni/a-private-repository.git

    - name: Compile test.c
      run: |
        gcc a-private-repository/test.c -o a-private-repository/test_program

    - name: Run compiled program
      run: |
        ./a-private-repository/test_program
